package find.cf.community.model;

public class TagCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAGCATEGORY.ID
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAGCATEGORY.CATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAGCATEGORY.REMARK
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAGCATEGORY.ID
     *
     * @return the value of TAGCATEGORY.ID
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAGCATEGORY.ID
     *
     * @param id the value for TAGCATEGORY.ID
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAGCATEGORY.CATEGORY
     *
     * @return the value of TAGCATEGORY.CATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAGCATEGORY.CATEGORY
     *
     * @param category the value for TAGCATEGORY.CATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAGCATEGORY.REMARK
     *
     * @return the value of TAGCATEGORY.REMARK
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAGCATEGORY.REMARK
     *
     * @param remark the value for TAGCATEGORY.REMARK
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}