package find.cf.community.mapper;

import find.cf.community.model.TagCategory;
import find.cf.community.model.TagCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TagCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    long countByExample(TagCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int deleteByExample(TagCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int insert(TagCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int insertSelective(TagCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    List<TagCategory> selectByExampleWithRowbounds(TagCategoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    List<TagCategory> selectByExample(TagCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    TagCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") TagCategory record, @Param("example") TagCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int updateByExample(@Param("record") TagCategory record, @Param("example") TagCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int updateByPrimaryKeySelective(TagCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGCATEGORY
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int updateByPrimaryKey(TagCategory record);
}