package find.cf.community.mapper;

import find.cf.community.model.Tags;
import find.cf.community.model.TagsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    long countByExample(TagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int deleteByExample(TagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int insert(Tags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int insertSelective(Tags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    List<Tags> selectByExampleWithRowbounds(TagsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    List<Tags> selectByExample(TagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    Tags selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tags record, @Param("example") TagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int updateByExample(@Param("record") Tags record, @Param("example") TagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int updateByPrimaryKeySelective(Tags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAGS
     *
     * @mbg.generated Sun Aug 25 11:56:17 CST 2019
     */
    int updateByPrimaryKey(Tags record);
}